name: CI CD Pipeline
permissions:
  id-token: write
  pages: write
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint application
        run: npm run ci:lint

      - name: Run tests
        run: npm run ci:test

      - name: Build application
        run: npm run ci:build

      - name: Rename index file to default
        run: mv github-pages/browser/index.csr.html github-pages/browser/index.html

      - name: Upload app artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: github-pages/browser/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
